name: Docker publish

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version changed before building
        id: check-version
        run: |
          current_version=$(jq -r .version package.json)
          previous_version=$(git show HEAD~1:package.json | jq -r .version)

          if [ "$current_version" != "$previous_version" ]; then
            echo "Package.json version bumped. Proceeding with Docker build."
            echo "BUILD_VERISON="$current_version" >> "$GITHUB_OUTPUT"
          else
            echo "Package.json version unchanged. Skipping Docker build."
            exit 0
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image tags
        uses: docker/build-push-action@v5
        env:
          VERSION: $(jq -r .version package.json)
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            xterna/${{ github.event.repository.name }}:latest
            xterna/${{ github.event.repository.name }}${ steps.check-version.outputs.BUILD_VERISON }}
